"""
Adversarial Scenario 3: Unauthenticated / Service-to-Service Access.

Attack family: a caller with no (or a bogus) credential tries to reach a
protected resource, or attempts to bypass the Policy Enforcement Point (Envoy)
by talking to the protected service directly.

Expected behaviour:
  * No Authorization header on a protected endpoint  -> 401/403
  * No Authorization header on a PUBLIC endpoint      -> 200 (public is open)
  * Empty / garbage bearer token                      -> 401
  * Direct access to the protected service (bypassing Envoy) is documented as
    a known lab limitation (no app-level auth); in production, mTLS on the
    service would refuse any client without a CA-signed certificate.

CyBOK AAA alignment: Authentication (no anonymous access to protected data),
Authorisation (PEP mediates every request), Enforcement (no network bypass).

NOTE: these tests exercise the running stack. Bring it up first:
  docker compose up -d --build
"""

import os

import httpx

from conftest import ENVOY_URL

PROTECTED_DIRECT_URL = os.getenv("PROTECTED_DIRECT_URL", "http://localhost:8000")

class TestUnauthenticatedServiceToService:

    def test_no_auth_header_returns_error(self, http_client):
        """A protected endpoint with no Authorization header must be refused."""
        resp = http_client.get(f"{ENVOY_URL}/api/data/reports")
        assert resp.status_code in (401, 403), (
            f"Protected endpoint without auth should return 401/403, "
            f"got {resp.status_code}."
        )

    def test_no_auth_header_public_endpoint(self, http_client):
        """A public endpoint must work with no Authorization header."""
        resp = http_client.get(f"{ENVOY_URL}/api/data/public")
        assert resp.status_code == 200, (
            f"Public endpoint should be reachable without auth (200), "
            f"got {resp.status_code}."
        )

    def test_empty_bearer_token(self, http_client):
        """A bearer scheme carrying no token must be rejected.

        Note: the literal value 'Bearer ' (scheme + trailing space, empty
        token) cannot be transmitted — HTTP/1.1 forbids trailing whitespace
        in a header value, so a compliant client (h11) raises before the
        request leaves the process, which itself stops the malformed
        credential from ever reaching a resource. We therefore assert on the
        nearest transmittable equivalent: the bare scheme 'Bearer' with no
        token, which the gateway must reject with 401.
        """
        resp = http_client.get(
            f"{ENVOY_URL}/api/data/reports",
            headers={"Authorization": "Bearer"},
        )
        assert resp.status_code == 401, (
            f"Bearer scheme with no token should return 401, got {resp.status_code}."
        )

    def test_garbage_token(self, http_client):
        """A non-JWT bearer value must be rejected."""
        resp = http_client.get(
            f"{ENVOY_URL}/api/data/reports",
            headers={"Authorization": "Bearer not-a-real-jwt-token"},
        )
        assert resp.status_code == 401, (
            f"Garbage token should return 401, got {resp.status_code}."
        )

    def test_direct_service_access_bypassing_envoy(self):
        """
        Attempt to reach the protected service directly, bypassing Envoy/OPA.

        In the lab the protected service does NOT enforce auth itself (it trusts
        the PEP), so a direct call typically succeeds — this test DOCUMENTS that
        as a known limitation rather than failing the suite. In production,
        mutual TLS on the service (certs already generated by
        scripts/generate-certs.sh) would reject any client lacking a CA-signed
        certificate, closing this bypass.
        """
        try:
            resp = httpx.get(f"{PROTECTED_DIRECT_URL}/api/data/admin", timeout=5.0)
        except httpx.HTTPError as exc:
            print(
                f"[direct-access] protected service unreachable directly: {exc!r} "
                f"— bypass is closed."
            )
            return

        if resp.status_code == 200:
            print(
                "[direct-access] KNOWN LIMITATION: the protected service is "
                "reachable directly on port 8000 without going through "
                "Envoy/OPA. The service trusts the PEP and performs no "
                "app-level auth. In production, enable mTLS "
                "(require_client_certificate) so only CA-signed clients "
                "(the api-gateway) can connect."
            )
        else:
            print(
                f"[direct-access] direct call returned {resp.status_code} "
                f"— service appears to enforce its own access control."
            )

        assert resp.status_code in (200, 401, 403), (
            f"Unexpected status from direct access: {resp.status_code}"
        )
